### ISSUE TITLE
Efficient Matrix Multipication

### ISSUE THREAD

**Issue by vgupta123** [ShelsonCao/DNGR#2]
for i = 1: max_step
    P = alpha*P*A + (1-alpha)*P0;
    M = M + P;
end

I guess it would be better to multiply two dense matrices rather than sparse(P) and dense matrix(A) for parallelization. 

Simple mdification
full(A);
full(P);
full(M);
full(P0);

followed by normal code.

**Comment by ShelsonCao** [comment]
Thanks for your suggestion! Actually, the input of our adjacent matrix is dense before we call DNGR function.
